# Generated by Django 3.0.7 on 2020-06-09 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 9, 0, 49, 0, 579062, tzinfo=utc), editable=False, verbose_name='created_at')),
                ('changed_at', models.DateTimeField(default=datetime.datetime(2020, 6, 9, 0, 49, 0, 579062, tzinfo=utc), editable=False, verbose_name='changed_at')),
                ('to_be_deleted', models.NullBooleanField(default=False, verbose_name='to be deleted')),
                ('changed_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_control_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed_by')),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_control_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('control_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Control')),
                ('name', models.CharField(default=None, max_length=100)),
                ('earnings_last_quarter', models.FloatField(default=0, null=True)),
                ('exceed_expectations_last_quarter', models.BooleanField(null=True)),
            ],
            bases=('base.control',),
        ),
    ]
