# Generated by Django 3.0.7 on 2020-06-09 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('control_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Control')),
                ('name', models.CharField(default=None, max_length=20)),
                ('closing_price', models.FloatField(default=None, null=True)),
                ('leveraged_free_cash_flow', models.FloatField(default=None, null=True)),
            ],
            bases=('base.control',),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='control',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 1, 10, 49, 532891, tzinfo=utc), editable=False, verbose_name='changed_at'),
        ),
        migrations.AlterField(
            model_name='control',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 1, 10, 49, 532891, tzinfo=utc), editable=False, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='company',
            name='ticker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Ticker'),
        ),
    ]
